name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn workspace system-props build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

  release:
    name: Publish to NPM
    needs: test
    # publish only when merged in master on original repo, not on PR
    if: github.repository == 'system-props/system-props' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn workspace system-props build
      - run: yarn workspace system-props semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
